export PATH=$HOME/Scripts:$HOME/.local/bin:/usr/local/bin:/opt/homebrew/bin:$PATH
export PATH=$PATH:/Users/rich/.spicetify
export PATH=.git/safe/../../bin::.git/safe/../../node_modules/.bin:$PATH
export TERMINFO_DIRS=$TERMINFO_DIRS:$HOME/.local/share/terminfo
export EDITOR=nvim
export DEFAULT_USER=`whoami`

for config_file ($HOME/.config/zsh/*.zsh) source $config_file

# asdf version manager (for ruby, node, elixir, etc).
[[ -f $HOME/.asdf/asdf.sh ]] && source $HOME/.asdf/asdf.sh
[[ -f $HOME/.asdf/completions/asdf.bash ]] && source $HOME/.asdf/completions/asdf.bash

if [[ -d /usr/share/fzf ]]; then
  source /usr/share/fzf/key-bindings.zsh
  source /usr/share/fzf/completion.zsh
fi

[ -f ~/.fzf.zsh ] && source ~/.fzf.zsh

if ! pgrep -u "$USER" ssh-agent > /dev/null; then
    ssh-agent -t 1h > "$HOME/.cache/ssh-agent.env"
fi
if [[ ! "$SSH_AUTH_SOCK" ]]; then
  [ -f "$HOME/.cache/ssh-agent.env" ] && source "$HOME/.cache/ssh-agent.env" >/dev/null
fi

# Local zsh settings.
[[ -s "$HOME/.zshrc.local" ]] && source "$HOME/.zshrc.local"
