#!/usr/bin/env bash

if ! updates=$(checkupdates 2> /dev/null | wc -l); then
  updates=0
fi

if ! yay_packages=$(yay -Qua 2> /dev/null | wc -l); then
  yay_packages=0
fi

# updates=25
# yay_packages=5

if [ "$updates" -gt 10 ] || [ "$yay_packages" -gt 10 ]; then
  echo "<span color=\"#f38ba8\">󰮯 $updates - ${yay_packages}</span>"
elif [ "$updates" -gt 0 ] || [ "$yay_packages" -gt 0 ]; then
  echo "󰮯 $updates - ${yay_packages}"
else
  echo ""
fi
