#!/bin/sh
git checkout -q main
git branch --merged | egrep -v '(\*|develop|master|main)' | xargs -I % git branch -d %
git for-each-ref refs/heads/ "--format=%(refname:short)" | while read branch; do
  mergeBase=$(git merge-base main $branch)
  if [[ $(git cherry main $(git commit-tree $(git rev-parse $branch^{tree}) -p $mergeBase -m _)) == "-"* ]]; then
    git branch -D $branch
  fi
done
