return {
  "RichGuk/harpoon",
  -- dev = true,
  event = "VeryLazy",
  branch = "harpoon2",
  dependencies = { "nvim-lua/plenary.nvim" },
  config = function()
    local harpoon = require("harpoon")
    harpoon.setup({})
    vim.keymap.set("n", "<leader>ha", function()
      harpoon:list():append()
    end, { desc = "Harpoon add file" })
    vim.keymap.set("n", "<leader>hc", function()
      harpoon:list():clear()
    end, { desc = "Harpoon clear list" })
    vim.keymap.set("n", "<leader>hh", function()
      harpoon.ui:toggle_quick_menu(harpoon:list())
    end, { desc = "Harpoon menu" })
    vim.keymap.set("n", "<leader>1", function()
      harpoon:list():select(1)
    end, { desc = "Harpoon file 1" })
    vim.keymap.set("n", "<leader>v1", function()
      harpoon:list():select(1, { vsplit = true })
    end, { desc = "Harpoon file 1 vsplit" })
    vim.keymap.set("n", "<leader>2", function()
      harpoon:list():select(2)
    end, { desc = "Harpoon file 2" })
    vim.keymap.set("n", "<leader>v2", function()
      harpoon:list():select(2, { vsplit = true })
    end, { desc = "Harpoon file 2 vsplit" })
    vim.keymap.set("n", "<leader>3", function()
      harpoon:list():select(3)
    end, { desc = "Harpoon file 3" })
    vim.keymap.set("n", "<leader>v3", function()
      harpoon:list():select(3, { vsplit = true })
    end, { desc = "Harpoon file 3 vsplit" })
    vim.keymap.set("n", "<leader>4", function()
      harpoon:list():select(4)
    end, { desc = "Harpoon file 4" })
    vim.keymap.set("n", "<leader>v4", function()
      harpoon:list():select(4, { vsplit = true })
    end, { desc = "Harpoon file 4 vsplit" })
    vim.keymap.set("n", "<leader>5", function()
      harpoon:list():select(5)
    end, { desc = "Harpoon file 5" })
    vim.keymap.set("n", "<leader>v5", function()
      harpoon:list():select(5, { vsplit = true })
    end, { desc = "Harpoon file 5 vsplit" })
    vim.keymap.set("n", "<leader>6", function()
      harpoon:list():select(6)
    end, { desc = "Harpoon file 6" })
    vim.keymap.set("n", "<leader>v6", function()
      harpoon:list():select(6, { vsplit = true })
    end, { desc = "Harpoon file 6 vsplit" })
  end,
}
